databases:
  - name: placetoplayapp
    region: frankfurt
    plan: free
    databaseName: placetoplayapp
    user: placetoplayapp
    

services:
  - type: web
    name: placetoplayapp
    env: ruby
    region: frankfurt
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: placetoplayapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false